---
- name: Configure nginx for ALB backend
  hosts: linux_servers
  become: yes
  gather_facts: yes
  vars:
    # ALB DNS name will be passed as extra var or retrieved from CloudFormation
    alb_dns: ""

  tasks:
    - name: Get CloudFormation stack outputs for ALB DNS name
      amazon.aws.cloudformation_info:
        stack_name: "has-kerberos-test-415"
        region: "ap-northeast-1"
      delegate_to: localhost
      register: cf_info
      when: alb_dns == ""

    - name: Set ALB DNS name from CloudFormation
      set_fact:
        alb_dns_name: "{{ cf_info.cloudformation['has-kerberos-test-415'].stack_outputs.ALBDNSName }}"
      when: alb_dns == "" and cf_info is defined

    - name: Set ALB DNS name from provided variable
      set_fact:
        alb_dns_name: "{{ alb_dns }}"
      when: alb_dns != ""

    - name: Display ALB configuration info
      debug:
        msg: |
          Configuring nginx for ALB backend
          ALB DNS Name: {{ alb_dns_name }}

    - name: Configure nginx for ALB with API proxy
      template:
        src: nginx-winauth-alb.conf.j2
        dest: /etc/nginx/conf.d/winauth.conf
        mode: '0644'
      notify: reload nginx

    - name: Remove any existing SSL certificates (not needed with ALB)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ssl/winauth/winauth.key
        - /etc/ssl/winauth/winauth.crt
        - /etc/ssl/winauth
      tags: cleanup_ssl

    - name: Test nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Display nginx test result
      debug:
        var: nginx_test

    - name: Reload nginx if configuration is valid
      systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0

    - name: Verify nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded