---
- name: Setup Group Policy for Intranet Zone
  hosts: domain_controllers
  gather_facts: no

  tasks:
    - name: Create GPO for Intranet Zone settings
      win_shell: |
        $albDomain = '{{ alb_dns_name }}'
        $gpoName = "Intranet Zone Settings"

        # Create GPO if not exists
        try {
            $gpo = Get-GPO -Name $gpoName -ErrorAction Stop
            Write-Output "GPO already exists: $gpoName"
        } catch {
            $gpo = New-GPO -Name $gpoName
            Write-Output "Created new GPO: $gpoName"
        }

        # Link GPO to domain if not already linked
        $domain = (Get-ADDomain).DistinguishedName
        $links = Get-GPInheritance -Target $domain
        $isLinked = $links.GpoLinks | Where-Object { $_.DisplayName -eq $gpoName }

        if (-not $isLinked) {
            New-GPLink -Name $gpoName -Target $domain -LinkEnabled Yes
            Write-Output "Linked GPO to domain: $domain"
        } else {
            Write-Output "GPO already linked to domain"
        }

        # Set registry values for Site to Zone Assignment
        $regPath = "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\$albDomain"

        Set-GPRegistryValue -Name $gpoName -Key $regPath -ValueName "*" -Type DWord -Value 1
        Set-GPRegistryValue -Name $gpoName -Key $regPath -ValueName "https" -Type DWord -Value 1

        # Set ZoneMap settings
        $zoneMapPath = "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap"
        Set-GPRegistryValue -Name $gpoName -Key $zoneMapPath -ValueName "IntranetName" -Type DWord -Value 1
        Set-GPRegistryValue -Name $gpoName -Key $zoneMapPath -ValueName "ProxyBypass" -Type DWord -Value 1
        Set-GPRegistryValue -Name $gpoName -Key $zoneMapPath -ValueName "UNCAsIntranet" -Type DWord -Value 1

        # Set Zone 1 settings
        $zone1Path = "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1"
        Set-GPRegistryValue -Name $gpoName -Key $zone1Path -ValueName "1A00" -Type DWord -Value 0
        Set-GPRegistryValue -Name $gpoName -Key $zone1Path -ValueName "1A10" -Type DWord -Value 0

        # Set Edge settings
        $edgePath = "HKCU\Software\Policies\Microsoft\Edge"
        Set-GPRegistryValue -Name $gpoName -Key $edgePath -ValueName "AuthNegotiateDelegateAllowlist" -Type String -Value $albDomain
        Set-GPRegistryValue -Name $gpoName -Key $edgePath -ValueName "AuthServerAllowlist" -Type String -Value $albDomain

        Write-Output "GPO configured successfully"
        Write-Output "ALB domain: $albDomain"
