---
- name: Add SPN for ALB DNS name
  hosts: domain_controllers
  gather_facts: no
  vars:
    service_account: "svcapp"

  tasks:
    - name: Get ALB DNS name from CloudFormation
      delegate_to: localhost
      become: no
      amazon.aws.cloudformation_info:
        stack_name: "{{ lookup('env', 'STACK_NAME') | default('has-kerberos-test-9606') }}"
      register: stack_info
      run_once: true
      when: inventory_hostname == 'dc1'

    - name: Set ALB DNS name fact
      set_fact:
        alb_dns_name: "{{ stack_info.cloudformation[lookup('env', 'STACK_NAME') | default('has-kerberos-test-9606')].stack_outputs.ALBDNSName }}"
      when: inventory_hostname == 'dc1' and stack_info is defined

    - name: Share ALB DNS name across hosts
      set_fact:
        alb_dns_name: "{{ hostvars['dc1']['alb_dns_name'] }}"
      when: inventory_hostname != 'dc1' and hostvars['dc1']['alb_dns_name'] is defined
    - name: Check existing SPNs
      win_shell: |
        setspn -L {{ service_account }}
      register: current_spns
      failed_when: false

    - name: Display current SPNs
      debug:
        var: current_spns.stdout_lines

    - name: Add HTTP SPN for ALB DNS name
      win_shell: |
        setspn -A HTTP/{{ alb_dns_name }} {{ service_account }}
      register: add_http_spn
      failed_when: false

    - name: Display HTTP SPN addition result
      debug:
        var: add_http_spn

    - name: Add HTTPS SPN for ALB DNS name
      win_shell: |
        setspn -A HTTPS/{{ alb_dns_name }} {{ service_account }}
      register: add_https_spn
      failed_when: false

    - name: Display HTTPS SPN addition result
      debug:
        var: add_https_spn

    - name: Verify final SPNs
      win_shell: |
        setspn -L {{ service_account }}
      register: final_spns

    - name: Display final SPNs
      debug:
        var: final_spns.stdout_lines