---
- name: Deploy WinAuth Linux Application Server
  hosts: linux_servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
      
    - name: Install required packages
      dnf:
        name:
          - git
          - docker
        state: present

    - name: Install Docker Compose plugin
      shell: |
        mkdir -p /usr/local/lib/docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
        chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
      args:
        creates: /usr/local/lib/docker/cli-plugins/docker-compose
    
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: "{{ app_user }}"
        groups: docker
        append: yes

    - name: Reset SSH connection to apply group changes
      meta: reset_connection

    - name: Set hostname
      hostname:
        name: "{{ app_hostname }}"

    - name: Add domain controllers to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        create: yes
      loop:
        - "{{ dc1_ip }} dc1.domain1.lab DOMAIN1.LAB"
        - "{{ dc2_ip }} dc2.domain2.lab DOMAIN2.LAB"
    
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Create config directory
      file:
        path: "{{ app_dir }}/config"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
    
    - name: Check if source directory is a git repository
      stat:
        path: "{{ app_dir }}/source/.git"
      register: git_repo_check

    - name: Remove old source directory if not a git repository
      file:
        path: "{{ app_dir }}/source"
        state: absent
      when: not git_repo_check.stat.exists

    - name: Clone or update WinAuth repository from GitHub
      git:
        repo: "https://github.com/oruharo/winauth.git"
        dest: "{{ app_dir }}/source"
        version: main
        force: yes
      become_user: "{{ app_user }}"

    - name: Create app config directory
      file:
        path: "{{ app_dir }}/app-config"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Create application configuration
      template:
        src: application.properties.j2
        dest: "{{ app_dir }}/app-config/application.properties"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'

    - name: Create NTLM application configuration
      template:
        src: application-ntlm.properties.j2
        dest: "{{ app_dir }}/app-config/application-ntlm.properties"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'

    - name: Stop all running Docker containers
      shell: docker stop $(docker ps -aq) || true
      ignore_errors: yes

    - name: Remove all Docker containers
      shell: docker rm $(docker ps -aq) || true
      ignore_errors: yes

    - name: Build Docker containers with verbose output
      shell: |
        cd {{ app_dir }}/source/ntlm
        docker compose build --no-cache
      become_user: "{{ app_user }}"
      async: 1800
      poll: 10
      register: docker_build

    - name: Start Docker containers
      shell: |
        cd {{ app_dir }}/source/ntlm
        docker compose up -d
      become_user: "{{ app_user }}"
      when: docker_build is succeeded



  handlers: