---
- name: Setup Windows Clients
  hosts: windows_clients
  gather_facts: no
  
  tasks:
    
    - name: Set DNS server to domain controller
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses: "{{ domain_controller }}"
        
    - name: Wait for DNS to propagate
      pause:
        seconds: 30
        
    - name: Join domain
      microsoft.ad.membership:
        dns_domain_name: "{{ target_domain }}"
        hostname: "{{ inventory_hostname | upper }}"
        domain_admin_user: "Administrator@{{ target_domain }}"
        domain_admin_password: "{{ admin_password }}"
        state: domain
      register: domain_join_result
      
    - name: Reboot after domain join
      win_reboot:
        reboot_timeout: 600
      when: domain_join_result.reboot_required
      
    - name: Add domain user to Remote Desktop Users group
      win_group_membership:
        name: "Remote Desktop Users"
        members:
          - "{{ target_domain | regex_replace('\\..*$', '') }}\\{{ domain_user }}"
        state: present

    - name: Register ALB domain in Intranet zone (HKCU)
      win_shell: |
        $albDomain = '{{ alb_dns_name }}'
        # Split domain into parts and reverse (e.g., example.com -> com\example)
        $parts = $albDomain -split '\.'
        [array]::Reverse($parts)
        $regPath = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains"
        foreach ($part in $parts) {
            $regPath = Join-Path $regPath $part
        }
        if (-not (Test-Path $regPath)) {
            New-Item -Path $regPath -Force | Out-Null
        }
        Set-ItemProperty -Path $regPath -Name '*' -Value 1 -Type DWord
        Set-ItemProperty -Path $regPath -Name 'https' -Value 1 -Type DWord
        Write-Output "Registered $albDomain in Intranet zone at $regPath"